# hello-go-deploy-aws-elastic-beanstalk task-unit-tests.yml

platform: linux

# DOCKER BASE IMAGE FOR TASKS (BASED ON ALPINE, A SMALLER LINUX DISTRIBUTION)
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.1

inputs:
  - name: hello-go-deploy-aws-elastic-beanstalk

outputs:
  - name: coverage-results

run:
  path: ./hello-go-deploy-aws-elastic-beanstalk/ci/scripts/unit-tests.sh
  # args: [-debug]
