# hello-go-deploy-aws-elastic-beanstalk task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11

inputs:
- name: hello-go-deploy-aws-elastic-beanstalk

outputs:
- name: hello-go-deploy-aws-elastic-beanstalk-updated

run:
  path: ./hello-go-deploy-aws-elastic-beanstalk/ci/scripts/readme-github-pages.sh
  # args: [-debug]

